# Generated by Django 4.2.16 on 2024-11-11 13:16

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
